## Numpy

In [2]:
# Import de la librairie et vérification de la version
import numpy as np
np.__version__

'1.26.4'

In [3]:
# Tableau à une dimension
tab_1d = np.array([5, 4, 2, 8])
print(tab_1d)

[5 4 2 8]


In [4]:
# Accès au premier élément
tab_1d[0] # Affiche 5

5

In [5]:
# Tableau à deux dimension
tab_2d = np.array([[5, 4, 2, 8],[7, 10, 3, 5],[8, 7, 4, 1]])
print(tab_2d)

[[ 5  4  2  8]
 [ 7 10  3  5]
 [ 8  7  4  1]]


In [6]:
# Accès au premier élément de mon tableau
print(tab_1d[0])

5


In [7]:
# Accès à la première ligne de mon tableau
print(tab_2d[0])

[5 4 2 8]


In [8]:
# Accès au premier élément de mon tableau
print(tab_2d[0][0])

5


In [9]:
np.shape(tab_2d)

(3, 4)

In [10]:
np.ndim(tab_2d)

2

In [11]:
np.size(tab_2d)

12

In [12]:
np.mean(tab_2d)

5.333333333333333

In [13]:
print(tab_2d[:, 0]) # Affiche [5 7 8]

[5 7 8]


In [14]:
print(tab_2d[0, :]) # Affiche [5 4 2 8]

[5 4 2 8]


In [15]:
print(tab_2d[:, 0:2]) # Affiche [[5 4][7 10][8 7]]

[[ 5  4]
 [ 7 10]
 [ 8  7]]


In [16]:
print(tab_2d[0:2, :]) # Affiche [[5 4 2 8][7 10 3 5]]

[[ 5  4  2  8]
 [ 7 10  3  5]]


In [17]:
print(tab_2d < 7)

[[ True  True  True False]
 [False False  True  True]
 [False False  True  True]]


In [18]:
# Tableau à deux dimension
tab_2d = np.array([[5, 4, 2, 8],[7, 10, 3, 5],[8, 7, 4, 1]])
print(tab_2d)

tab_2d[tab_2d < 7] = 3
print(tab_2d)

[[ 5  4  2  8]
 [ 7 10  3  5]
 [ 8  7  4  1]]
[[ 3  3  3  8]
 [ 7 10  3  3]
 [ 8  7  3  3]]


In [19]:
# Tableau à deux dimension
tab_2d = np.array([[5, 4, 2, 8],[7, 10, 3, 5],[8, 7, 4, 1]])
print(tab_2d)

tab_2d[(tab_2d < 7) & (tab_2d > 3)] = 3
print(tab_2d)

[[ 5  4  2  8]
 [ 7 10  3  5]
 [ 8  7  4  1]]
[[ 3  3  2  8]
 [ 7 10  3  3]
 [ 8  7  3  1]]


In [20]:
tab_2d = np.array([[5, 4, 2, 8],[7, 10, 3, 5],[8, 7, 4, 1]])
np.sum(tab_2d)

64

In [21]:
np.prod(tab_2d)

75264000

In [22]:
np.sin(tab_2d)

array([[-0.95892427, -0.7568025 ,  0.90929743,  0.98935825],
       [ 0.6569866 , -0.54402111,  0.14112001, -0.95892427],
       [ 0.98935825,  0.6569866 , -0.7568025 ,  0.84147098]])

In [23]:
np.cos(tab_2d)

array([[ 0.28366219, -0.65364362, -0.41614684, -0.14550003],
       [ 0.75390225, -0.83907153, -0.9899925 ,  0.28366219],
       [-0.14550003,  0.75390225, -0.65364362,  0.54030231]])

In [24]:
np.exp(tab_2d)

array([[1.48413159e+02, 5.45981500e+01, 7.38905610e+00, 2.98095799e+03],
       [1.09663316e+03, 2.20264658e+04, 2.00855369e+01, 1.48413159e+02],
       [2.98095799e+03, 1.09663316e+03, 5.45981500e+01, 2.71828183e+00]])

In [25]:
np.log(tab_2d)

array([[1.60943791, 1.38629436, 0.69314718, 2.07944154],
       [1.94591015, 2.30258509, 1.09861229, 1.60943791],
       [2.07944154, 1.94591015, 1.38629436, 0.        ]])

In [26]:
np.mean(tab_2d)

5.333333333333333

In [30]:
np.median(tab_2d)

2.592724864350674

In [31]:
np.var(tab_2d)

6.722222222222222

In [32]:
np.std(tab_2d)

2.592724864350674

In [33]:
np.corrcoef(tab_2d)

array([[ 1.        ,  0.1004662 , -0.46380072],
       [ 0.1004662 ,  1.        ,  0.63540406],
       [-0.46380072,  0.63540406,  1.        ]])

In [37]:
np.sum(tab_2d, axis=0)


array([19, 25, 20])

In [38]:
np.sum(tab_2d, axis=1)

array([19, 25, 20])

In [39]:
np.unique(tab_2d, return_counts=True)

(array([ 1,  2,  3,  4,  5,  7,  8, 10]),
 array([1, 1, 1, 2, 2, 2, 2, 1], dtype=int64))

In [54]:
data = np.loadtxt("data.csv", delimiter=',', skiprows=1)
print(data)

[[ 1.  0. 10.]
 [ 2.  0.  8.]
 [ 3.  5.  3.]
 [ 4.  2.  5.]
 [ 5. 10.  1.]
 [ 6. 50.  0.]
 [ 7.  0. 10.]]


Bien sûr! Voici quelques exercices pour vous aider à maîtriser NumPy. Ces exercices couvrent différents aspects de la bibliothèque, des bases aux opérations plus avancées.

### **Exercice 1: Création et Manipulation de Tableaux**
1. **Créer un tableau 1D** de 10 éléments contenant les nombres de 0 à 9.
   ```python
   import numpy as np
   array_1d = np.arange(10)
   print(array_1d)
   ```

2. **Créer un tableau 2D** de dimensions 3x3 contenant des nombres aléatoires entre 0 et 1.
   ```python
   array_2d = np.random.rand(3, 3)
   print(array_2d)
   ```

3. **Redimensionner** le tableau 1D créé en un tableau 2D de dimensions 2x5.
   ```python
   reshaped_array = array_1d.reshape(2, 5)
   print(reshaped_array)
   ```

### **Exercice 2: Opérations sur les Tableaux**
1. **Ajouter 5** à chaque élément du tableau 1D.
   ```python
   array_plus_5 = array_1d + 5
   print(array_plus_5)
   ```

2. **Multiplier** chaque élément du tableau 2D par 10.
   ```python
   array_2d_multiplied = array_2d * 10
   print(array_2d_multiplied)
   ```

3. **Calculer la somme** de tous les éléments du tableau 2D.
   ```python
   sum_2d = np.sum(array_2d)
   print(sum_2d)
   ```

### **Exercice 3: Indexation et Slicing**
1. **Extraire les éléments** du tableau 1D de l'indice 2 à l'indice 5.
   ```python
   sliced_array = array_1d[2:6]
   print(sliced_array)
   ```

2. **Extraire la première colonne** du tableau 2D.
   ```python
   first_column = array_2d[:, 0]
   print(first_column)
   ```

3. **Modifier les éléments** de la deuxième ligne du tableau 2D pour qu'ils soient tous égaux à 0.
   ```python
   array_2d[1, :] = 0
   print(array_2d)
   ```

### **Exercice 4: Fonctions Mathématiques et Statistiques**
1. **Calculer la moyenne** des éléments du tableau 1D.
   ```python
   mean_1d = np.mean(array_1d)
   print(mean_1d)
   ```

2. **Calculer l'écart-type** des éléments du tableau 2D.
   ```python
   std_2d = np.std(array_2d)
   print(std_2d)
   ```

3. **Trouver l'élément maximum** et son indice dans le tableau 1D.
   ```python
   max_value = np.max(array_1d)
   max_index = np.argmax(array_1d)
   print(max_value, max_index)
   ```

### **Exercice 5: Génération de Données**
1. **Créer un tableau** de 20 éléments contenant des nombres aléatoires entiers entre 1 et 100.
   ```python
   random_integers = np.random.randint(1, 101, size=20)
   print(random_integers)
   ```

2. **Créer une matrice identité** de dimensions 4x4.
   ```python
   identity_matrix = np.eye(4)
   print(identity_matrix)
   ```

3. **Générer une séquence** de 50 nombres également espacés entre 0 et 10.
   ```python
   linspace_array = np.linspace(0, 10, 50)
   print(linspace_array)
   ```

Ces exercices devraient vous aider à bien comprendre et maîtriser les fonctionnalités de base et avancées de NumPy. N'hésitez pas à me demander si vous avez des questions ou besoin d'aide supplémentaire!

Atelier Pratique
Exercices
Création d'un Tableau :

Créez un tableau NumPy contenant les nombres de 0 à 9.
Opérations de Base :

Multipliez chaque élément du tableau par 2.
Indexation et Slicing :

Extrayez les éléments de la position 2 à 5 du tableau.
Reshape et Flatten :

Transformez le tableau en une matrice de 2x5 et applatissez-la ensuite.
Calculs :

Calculez la somme, le minimum et le maximum du tableau.
Solutions
Création d'un Tableau :

python
Copy Code
import numpy as np
ex1 = np.arange(10)
print(ex1)
# Output: [0 1 2 3 4 5 6 7 8 9]
Opérations de Base :

python
Copy Code
ex2 = ex1 * 2
print(ex2)
# Output: [ 0  2  4  6  8 10 12 14 16 18]
Indexation et Slicing :

python
Copy Code
ex3 = ex1[2:6]
print(ex3)
# Output: [2 3 4 5]
Reshape et Flatten :

python
Copy Code
ex4 = ex1.reshape((2, 5))
print(ex4)
# Output: 
# [[0 1 2 3 4]
#  [5 6 7 8 9]]
ex4_flattened = ex4.flatten()
print(ex4_flattened)
# Output: [0 1 2 3 4 5 6 7 8 9]
Calculs :

python
Copy Code
ex5_sum = np.sum(ex1)
ex5_min = np.min(ex1)
ex5_max = np.max(ex1)
print(ex5_sum)  # Output: 45
print(ex5_min)  # Output: 0
print(ex5_max)  # Output: 9
En suivant ce chapitre et en réalisant les exercices, vous aurez une bonne compréhension des bases de NumPy et de son utilisation pour le calcul scientifique en Python.