## Numpy

In [2]:
# Import de la librairie et vérification de la version
import numpy as np
np.__version__

'1.26.4'

In [3]:
# Tableau à une dimension
tab_1d = np.array([5, 4, 2, 8])
print(tab_1d)

[5 4 2 8]


In [4]:
# Accès au premier élément
tab_1d[0] # Affiche 5

5

In [5]:
# Tableau à deux dimension
tab_2d = np.array([[5, 4, 2, 8],[7, 10, 3, 5],[8, 7, 4, 1]])
print(tab_2d)

[[ 5  4  2  8]
 [ 7 10  3  5]
 [ 8  7  4  1]]


In [6]:
# Accès au premier élément de mon tableau
print(tab_1d[0])

5


In [7]:
# Accès à la première ligne de mon tableau
print(tab_2d[0])

[5 4 2 8]


In [8]:
# Accès au premier élément de mon tableau
print(tab_2d[0][0])

5


In [9]:
np.shape(tab_2d)

(3, 4)

In [10]:
np.ndim(tab_2d)

2

In [11]:
np.size(tab_2d)

12

In [12]:
np.mean(tab_2d)

5.333333333333333

In [13]:
print(tab_2d[:, 0]) # Affiche [5 7 8]

[5 7 8]


In [14]:
print(tab_2d[0, :]) # Affiche [5 4 2 8]

[5 4 2 8]


In [15]:
print(tab_2d[:, 0:2]) # Affiche [[5 4][7 10][8 7]]

[[ 5  4]
 [ 7 10]
 [ 8  7]]


In [16]:
print(tab_2d[0:2, :]) # Affiche [[5 4 2 8][7 10 3 5]]

[[ 5  4  2  8]
 [ 7 10  3  5]]


In [17]:
print(tab_2d < 7)

[[ True  True  True False]
 [False False  True  True]
 [False False  True  True]]


In [18]:
# Tableau à deux dimension
tab_2d = np.array([[5, 4, 2, 8],[7, 10, 3, 5],[8, 7, 4, 1]])
print(tab_2d)

tab_2d[tab_2d < 7] = 3
print(tab_2d)

[[ 5  4  2  8]
 [ 7 10  3  5]
 [ 8  7  4  1]]
[[ 3  3  3  8]
 [ 7 10  3  3]
 [ 8  7  3  3]]


In [19]:
# Tableau à deux dimension
tab_2d = np.array([[5, 4, 2, 8],[7, 10, 3, 5],[8, 7, 4, 1]])
print(tab_2d)

tab_2d[(tab_2d < 7) & (tab_2d > 3)] = 3
print(tab_2d)

[[ 5  4  2  8]
 [ 7 10  3  5]
 [ 8  7  4  1]]
[[ 3  3  2  8]
 [ 7 10  3  3]
 [ 8  7  3  1]]


In [20]:
tab_2d = np.array([[5, 4, 2, 8],[7, 10, 3, 5],[8, 7, 4, 1]])
np.sum(tab_2d)

64

In [21]:
np.prod(tab_2d)

75264000

In [22]:
np.sin(tab_2d)

array([[-0.95892427, -0.7568025 ,  0.90929743,  0.98935825],
       [ 0.6569866 , -0.54402111,  0.14112001, -0.95892427],
       [ 0.98935825,  0.6569866 , -0.7568025 ,  0.84147098]])

In [23]:
np.cos(tab_2d)

array([[ 0.28366219, -0.65364362, -0.41614684, -0.14550003],
       [ 0.75390225, -0.83907153, -0.9899925 ,  0.28366219],
       [-0.14550003,  0.75390225, -0.65364362,  0.54030231]])

In [24]:
np.exp(tab_2d)

array([[1.48413159e+02, 5.45981500e+01, 7.38905610e+00, 2.98095799e+03],
       [1.09663316e+03, 2.20264658e+04, 2.00855369e+01, 1.48413159e+02],
       [2.98095799e+03, 1.09663316e+03, 5.45981500e+01, 2.71828183e+00]])

In [25]:
np.log(tab_2d)

array([[1.60943791, 1.38629436, 0.69314718, 2.07944154],
       [1.94591015, 2.30258509, 1.09861229, 1.60943791],
       [2.07944154, 1.94591015, 1.38629436, 0.        ]])

In [26]:
np.mean(tab_2d)

5.333333333333333

In [30]:
np.median(tab_2d)

2.592724864350674

In [31]:
np.var(tab_2d)

6.722222222222222

In [32]:
np.std(tab_2d)

2.592724864350674

In [33]:
np.corrcoef(tab_2d)

array([[ 1.        ,  0.1004662 , -0.46380072],
       [ 0.1004662 ,  1.        ,  0.63540406],
       [-0.46380072,  0.63540406,  1.        ]])

In [37]:
np.sum(tab_2d, axis=0)


array([19, 25, 20])

In [38]:
np.sum(tab_2d, axis=1)

array([19, 25, 20])

In [39]:
np.unique(tab_2d, return_counts=True)

(array([ 1,  2,  3,  4,  5,  7,  8, 10]),
 array([1, 1, 1, 2, 2, 2, 2, 1], dtype=int64))

In [54]:
data = np.loadtxt("data.csv", delimiter=',', skiprows=1)
print(data)

[[ 1.  0. 10.]
 [ 2.  0.  8.]
 [ 3.  5.  3.]
 [ 4.  2.  5.]
 [ 5. 10.  1.]
 [ 6. 50.  0.]
 [ 7.  0. 10.]]
