In [1]:
import numpy as np

# Création d'un tableau 1D
a = np.array([1, 2, 3, 4, 5])

# Création d'un tableau 2D (Matrice)
b = np.array([[1, 2, 3], [4, 5, 6]])

print(a)
print(b)



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
# Accès à un élément du tableau 1D
print(a[2])  # Sortie: 3
    
# Accès à un élément du tableau 2D
print(b[1, 2])  # Sortie: 6


3
6


In [9]:
 b_reshaped = b.reshape(3, 2)
#print(b_reshaped)
print(f"b transformé : \n{b_reshaped}")

# Transpose
b_transposed = b.T
print(f"b transposé : \n{b_transposed}")


b transformé : 
[[1 2]
 [3 4]
 [5 6]]
b transposé : 
[[1 4]
 [2 5]
 [3 6]]
