Voici quelques exercices pour vous aider à maîtriser NumPy. Ces exercices couvrent différents aspects de la bibliothèque, des bases aux opérations plus avancées.

### Exercice 1: Création et manipulation de tableaux

In [1]:
# 1. **Créer un tableau 1D** de 10 éléments contenant les nombres de 0 à 9.

import numpy as np
array_1d = np.arange(10)
print(array_1d)


# 2. **Créer un tableau 2D** de dimensions 3x3 contenant des nombres aléatoires entre 0 et 1.
 
array_2d = np.random.rand(3, 3)
print(array_2d)


# 3. **Redimensionner** le tableau 1D créé en un tableau 2D de dimensions 2x5.

reshaped_array = array_1d.reshape(2, 5)
print(reshaped_array)


[0 1 2 3 4 5 6 7 8 9]
[[0.785512   0.78048153 0.67931515]
 [0.8400485  0.08852692 0.81588159]
 [0.31021488 0.69996155 0.10106837]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercice 2: Opérations sur les Tableaux


In [ ]:
# 1. **Ajouter 5** à chaque élément du tableau 1D.
 
array_plus_5 = array_1d + 5
print(array_plus_5)


# 2. **Multiplier** chaque élément du tableau 2D par 10.

array_2d_multiplied = array_2d * 10
print(array_2d_multiplied)


# 3. **Calculer la somme** de tous les éléments du tableau 2D.

sum_2d = np.sum(array_2d)
print(sum_2d)

### Exercice 3: Indexation et découpage

In [ ]:
# 1. **Extraire les éléments** du tableau 1D de l'indice 2 à l'indice 5.

sliced_array = array_1d[2:6]
print(sliced_array)


# 2. **Extraire la première colonne** du tableau 2D.

first_column = array_2d[:, 0]
print(first_column)


# 3. **Modifier les éléments** de la deuxième ligne du tableau 2D pour qu'ils soient tous égaux à 0.

array_2d[1, :] = 0
print(array_2d)


### Exercice 4: Fonctions mathématiques et statistiques

In [ ]:
# 1. **Calculer la moyenne** des éléments du tableau 1D.
 
mean_1d = np.mean(array_1d)
print(mean_1d)
 

# 2. **Calculer l'écart-type** des éléments du tableau 2D.
 
std_2d = np.std(array_2d)
print(std_2d)


# 3. **Trouver l'élément maximum** et son indice dans le tableau 1D.

max_value = np.max(array_1d)
max_index = np.argmax(array_1d)
print(max_value, max_index)
   

# 4. **Trouver l'élément minimum** et son indice dans le tableau 1D.
 
min_value = np.min(array_1d)
min_index = np.argmin(array_1d)
print(min_value, min_index)
   

# 5. **Calculez la somme**  du tableau 1D

tab_sum = np.sum(array_1d)
print(tab_sum)  


### Exercice 5: Génération de données

In [ ]:
# 1. **Créer un tableau** de 20 éléments contenant des nombres aléatoires entiers entre 1 et 100.

random_integers = np.random.randint(1, 101, size=20)
print(random_integers)


# 2. **Créer une matrice identité** de dimensions 4x4.

identity_matrix = np.eye(4)
print(identity_matrix)


# 3. **Générer une séquence** de 50 nombres également espacés entre 0 et 10.

linspace_array = np.linspace(0, 10, 50)
print(linspace_array)
